# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6c092cdbf522fc1505d486791271edabf879f1f2da96f76efa77bc43e13aebc68680187a926562571fcfd0287472dbdd358d1a43e47a9dd2dcf2f9fef960ae7

test:
  secret_key_base: 243105072c808f3ecfd7a1af9a8186df8f5e6f44882e95e4c92d59893da840a1b0e117906d916fbe3036530cb993c6d09087d7bf8f38b981bc7f49a154e967e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
